# ai-trader config
watchlist:
  - AAPL
  - MSFT
  - TSLA
thresholds:
  volume_spike: 2.0
  rsi_window: 14
  atr_window: 14
  vwap_window: 20
strategy:
  breakout_lookback: 20
  trailing_atr_mult: 2.0
options:
  min_days: 14
  min_delta: 0.4
  min_oi: 200
  max_spread: 0.1
discord:
  webhook_url: YOUR_DISCORD_WEBHOOK_URL
  # server_id: Set in .env as DISCORD_SERVER_ID
  # stocks_channel_id: Set in .env as DISCORD_STOCKS_CHANNEL_ID
  # options_channel_id: Set in .env as DISCORD_OPTIONS_CHANNEL_ID
  # futures_channel_id: Set in .env as DISCORD_FUTURES_CHANNEL_ID
  # general_channel_id: Set in .env as DISCORD_GENERAL_CHANNEL_ID
unusual_whales:
  enabled: true
